[package]
name = "reth-revm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "reth specific revm utilities"

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-primitives.workspace = true
reth-storage-errors.workspace = true
reth-execution-errors.workspace = true
reth-consensus-common.workspace = true
reth-prune-types.workspace = true
reth-storage-api.workspace = true
reth-trie = { workspace = true, optional = true }

# fluentbase
fluentbase-sdk.workspace = true

# revm
revm.workspace = true

# alloy
alloy-eips.workspace = true
alloy-rlp.workspace = true

# common
tracing.workspace = true

[dev-dependencies]
reth-trie.workspace = true

[features]
test-utils = ["dep:reth-trie"]
rwasm = ["reth-primitives/rwasm"]
